package applicationMain;

import javafx.application.Application;
import javafx.stage.Stage;

/*******
 * <p> Title: DiscussionMain Class </p>
 *
 * <p> Description: Standalone JavaFX entry point for the discussion CRUD
 * demonstration. This application is independent of the Foundations login and
 * database logic and uses an in-memory model defined in the guiDiscussion
 * package.</p>
 *
 * <p> Copyright: Lynn Robert Carter © 2025 </p>
 *
 * @author Generated by AI assistant
 *
 * @version 1.00 2026-02-24 Initial MVC-based standalone main class.
 */
public class DiscussionMain extends Application {

	/** Default application window width in pixels. */
	public final static double WINDOW_WIDTH = 800;
	/** Default application window height in pixels. */
	public final static double WINDOW_HEIGHT = 600;

	@Override
	public void start(Stage primaryStage) {
		guiDiscussion.ViewDiscussion.displayHome(primaryStage);
	}

	/*******
	 * <p> Title: DiscussionMain main method that starts up JavaFX</p>
	 *
	 * @param args The array of command line parameters. These are not used.
	 */
	public static void main(String[] args) {
		launch(args);
	}
}

